# This is a basic workflow to help you get started with Actions

name: QA CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: QA Image build
        id: image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo ${{ github.ref }}
          echo ${{ github.sha }} | cut -c1-8
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
  deploy:
  
    runs-on: ubuntu-latest
    needs: build
    steps:
      
      - name: Get image version
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo ${{ github.ref }}
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"

      - name: Checkout deploy repository
        uses: actions/checkout@v2
        with:
          repository: wlgns5376/k8s-deploy-test
          token: ${{ secrets.ACTION_TOKEN }}
          path: k8s-deploy-test

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Update Kubernetes resources
        run: |
          cd k8s-deploy-test
          kustomize edit set image app=wlgns5376/docker-image:${{ steps.image.outputs.version }}
          cat kustomization.yaml

      - name: Commit files
        run: |
          cd k8s-deploy-test
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit -am "Update image tag"
          git push -u origin main
